name: Windows Build

on:
  push

jobs:
  windows-build:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Prepare
      run: .ci/prepare-windows.bat
    - name: Bootstrap vcpkg
      run: C:\vcpkg\bootstrap-vcpkg.bat
    - name: Meson Setup
      env:
        PKG_CONFIG: C:\vcpkg\installed\x64-windows\tools\pkgconf\pkgconf.exe
        PKG_CONFIG_PATH: C:\vcpkg\installed\x64-windows\lib\pkgconfig
      run: meson setup --backend vs2022 --buildtype debugoptimized builddir -Dcmake_toolchain_file=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
    - name: MSBuild Setup for Meson
      uses: microsoft/setup-msbuild@v3
    - name: Meson Compile
      run: meson compile -C builddir
